* Gabapentin Study *
* make data *
* written 2018.6.15 *
* updated 2019.12.24 *
* By Yifan Zhang *
set more off
log using "G:\Gabapentin\analysis\makedata.smcl", replace
use "G:\Gabapentin\statadata\2016.10.1-2017.3.31.dta"

* limite to 2016/12/1 to 2017/3/31
gen int DateFilled_d = date(DateFilled, "MDY")
format DateFilled_d %td
drop DateFilled
rename DateFilled_d DateFilled
gen int DateWritten_d = date(DateWritten, "MDY")
format DateWritten_d %td
drop DateWritten
rename DateWritten_d DateWritten

drop if DateFilled < td(1dec2016)
gen DrugClass=99
label define DrugClass 0"Opioids" 1"Benzodiazepine" 2"Stimulants" 3"Anti-Depression" 4"Muscle-Relaxant" 5 "Gabapentin" 99 "Others"
label values DrugClass DrugClass

replace DrugClass=. if TherClassDesc=="Blank"
replace DrugClass=. if TherClassDesc=="Unspecified (0000000000)"

replace DrugClass=0 if TherClassDesc=="Codeine/Guaifenesin & Comb."
replace DrugClass=0 if TherClassDesc=="Buprenorphine & Comb."
replace DrugClass=0 if TherClassDesc=="Butorphanol Tartrate"
replace DrugClass=0 if TherClassDesc=="Codeine & Comb. (2808080010)"
replace DrugClass=0 if TherClassDesc=="Codeine & Comb. (4808010020)"
replace DrugClass=0 if TherClassDesc=="Difenoxin/Atropine"
replace DrugClass=0 if TherClassDesc=="Dihydrocodeine & Comb. (2808080012)"
replace DrugClass=0 if TherClassDesc=="Dihydrocodeine & Comb. (4808010027)"
replace DrugClass=0 if TherClassDesc=="Fentanyl & Comb."
replace DrugClass=0 if TherClassDesc=="Hydrocod/Guaifenesin & Comb."
replace DrugClass=0 if TherClassDesc=="Hydrocodone & Comb. (2808080020)"
replace DrugClass=0 if TherClassDesc=="Hydrocodone & Comb. (4808010040)"
replace DrugClass=0 if TherClassDesc=="Hydromorph/Guaifenesin & Comb."
replace DrugClass=0 if TherClassDesc=="Hydromorphone & Comb."
replace DrugClass=0 if TherClassDesc=="Levorphanol"
replace DrugClass=0 if TherClassDesc=="Methadone"
replace DrugClass=0 if TherClassDesc=="Morphine Sulfate & Comb."
replace DrugClass=0 if TherClassDesc=="Nalbuphine"
replace DrugClass=0 if TherClassDesc=="Oxycodone & Comb."
replace DrugClass=0 if TherClassDesc=="Oxymorphone"
replace DrugClass=0 if TherClassDesc=="Paregoric & Comb."
replace DrugClass=0 if TherClassDesc=="Pentazocine & Comb"
replace DrugClass=0 if TherClassDesc=="Pentazocine & Comb."
replace DrugClass=0 if TherClassDesc=="Remifentanil"
replace DrugClass=0 if TherClassDesc=="Tapentadol"
replace DrugClass=0 if TherClassDesc=="Tramadol"
replace DrugClass=0 if TherClassDesc=="Paregoric & Comb."
replace DrugClass=0 if TherClassDesc=="Cocaine, EENT"
replace DrugClass=0 if TherClassDesc=="Codeine/Guaifenesin & Comb."
replace DrugClass=0 if TherClassDesc=="Codeine/Iodinated Glycerol"
replace DrugClass=0 if TherClassDesc=="Meperidine & Comb."
replace DrugClass=0 if TherClassDesc=="Opium Preparations"
replace DrugClass=0 if TherClassDesc=="Propoxyphene & Comb."
replace DrugClass=0 if TherClassDesc=="Diphenoxylate/Atropine"

replace DrugClass=1 if TherClassDesc=="Alprazolam"
replace DrugClass=1 if TherClassDesc=="Clobazam"
replace DrugClass=1 if TherClassDesc=="Clonazepam"
replace DrugClass=1 if TherClassDesc=="Diazepam"
replace DrugClass=1 if TherClassDesc=="Estazolam"
replace DrugClass=1 if TherClassDesc=="Flurazepam"
replace DrugClass=1 if TherClassDesc=="Lorazepam"
replace DrugClass=1 if TherClassDesc=="Midazolam"
replace DrugClass=1 if TherClassDesc=="Oxazepam"
replace DrugClass=1 if TherClassDesc=="Quazepam"
replace DrugClass=1 if TherClassDesc=="Temazepam"
replace DrugClass=1 if TherClassDesc=="Triazolam"
replace DrugClass=1 if TherClassDesc=="Chlordiazepoxide"
replace DrugClass=1 if TherClassDesc=="Clorazepate & Comb."

replace DrugClass=2 if TherClassDesc=="Armodafinil"
replace DrugClass=2 if TherClassDesc=="Benzphetamine"
replace DrugClass=2 if TherClassDesc=="Desoxyephedrine"
replace DrugClass=2 if TherClassDesc=="Dexmethylphenidate"
replace DrugClass=2 if TherClassDesc=="Dextroamphetamine"
replace DrugClass=2 if TherClassDesc=="Ephedrine & Comb."
replace DrugClass=2 if TherClassDesc=="Lisdexamfetamine"
replace DrugClass=2 if TherClassDesc=="Methamphetamine"
replace DrugClass=2 if TherClassDesc=="Methenamine & Comb."
replace DrugClass=2 if TherClassDesc=="Methylphenidate"
replace DrugClass=2 if TherClassDesc=="Modafinil"
replace DrugClass=2 if TherClassDesc=="Pemoline"
replace DrugClass=2 if TherClassDesc=="Phentermine"
replace DrugClass=2 if TherClassDesc=="Amphetamine & Comb."

replace DrugClass=3 if TherClassDesc=="Amitriptyline & Comb."
replace DrugClass=3 if TherClassDesc=="Amoxapine"
replace DrugClass=3 if TherClassDesc=="Antidepressants"
replace DrugClass=3 if TherClassDesc=="Bupropion"
replace DrugClass=3 if TherClassDesc=="Citalopram"
replace DrugClass=3 if TherClassDesc=="Clomipramine"
replace DrugClass=3 if TherClassDesc=="Desipramine"
replace DrugClass=3 if TherClassDesc=="Desvenlafaxine"
replace DrugClass=3 if TherClassDesc=="Donepezil"
replace DrugClass=3 if TherClassDesc=="Doxepin (2816040820)"
replace DrugClass=3 if TherClassDesc=="Doxepin (2824920016)"
replace DrugClass=3 if TherClassDesc=="Doxepin, S/M"
replace DrugClass=3 if TherClassDesc=="Duloxetine HCl"
replace DrugClass=3 if TherClassDesc=="Escitalopram"
replace DrugClass=3 if TherClassDesc=="Fluoxetine"
replace DrugClass=3 if TherClassDesc=="Fluvoxamine Maleate"
replace DrugClass=3 if TherClassDesc=="Imipramine"
replace DrugClass=3 if TherClassDesc=="Mirtazapine"
replace DrugClass=3 if TherClassDesc=="Nortriptyline"
replace DrugClass=3 if TherClassDesc=="Paroxetine"
replace DrugClass=3 if TherClassDesc=="Protriptyline"
replace DrugClass=3 if TherClassDesc=="Sertraline"
replace DrugClass=3 if TherClassDesc=="Venlafaxine HCl"

replace DrugClass=4 if TherClassDesc=="Chlorzoxazone & Comb."
replace DrugClass=4 if TherClassDesc=="Baclofen"
replace DrugClass=4 if TherClassDesc=="Carisoprodol & Comb."
replace DrugClass=4 if TherClassDesc=="Chlorzoxazone & Comb."
replace DrugClass=4 if TherClassDesc=="Cyclobenzaprine"
replace DrugClass=4 if TherClassDesc=="Dantrolene Sodium"
replace DrugClass=4 if TherClassDesc=="Metaxalone"
replace DrugClass=4 if TherClassDesc=="Tizanidine"
replace DrugClass=4 if TherClassDesc=="Methocarbamol & Comb."


replace DrugClass=0 if Drug=="BUPRENORPHINE  POW"
replace DrugClass=0 if Drug=="CODEINE  POW"
replace DrugClass=0 if Drug=="FENTANYL  POW"
replace DrugClass=0 if Drug=="FENTANYL BASE  CRY"
replace DrugClass=0 if Drug=="HYDROCODONE BI  POW"
replace DrugClass=0 if Drug=="HYDROMORPHONE  POW"
replace DrugClass=0 if Drug=="MORPHINE  POW"
replace DrugClass=0 if Drug=="OXYCODONE  POW"
replace DrugClass=0 if Drug=="SUFENTANIL  POW"

replace DrugClass=1 if Drug=="DIAZEPAM  POW"
replace DrugClass=1 if Drug=="LORAZEPAM  POW"
replace DrugClass=2 if Drug=="METHYLPHENIDATE  POW"

replace DrugClass=5 if TherClassDesc=="Gabapentin"

codebook PatientGroupIDHash
* Eligible population
* 1) Exclude Rx from veterinarians
*    The Mandatory OARRS Registration and Requests law DOES NOT apply to veterinarians.
drop if PrescriberSpecialty == "Veterinarian"

* Dataset contains only Ohio patients
* 2) limit to patients who filled at least one gabapentin
gen GabRx = .
replace GabRx = 1 if DrugClass == 5
egen GabPop = max(GabRx), by(PatientGroupIDHash)

* 3) excluding terminal patient.
gen PallRx = .
replace PallRx = 1 if PrescriberSpecialty == "Palliative Medicine" | PrescriberSpecialty == "Hospice"
egen PallPat = max(PallRx), by(PatientGroupIDHash)

gen ElgPop = 1 if GabPop == 1 & PallPat != 1
keep if ElgPop == 1
codebook PatientGroupIDHash

****** Opioid Type *****


gen OpioidType=.
label define OpioidType 1"Buprenorphine" 2"Butorphanol" 3 "Codeine" 4 "Proxyphene" 5 "Difenoxin" 6 "Dihydrocodeine" 7 "Diphenoxylate" 8 "Fentanyl" 9 "Hydrocodone" 10 "Hydromorphone" 11 "Levorphanol" 12 "Meperidine" 13 "Methadone" 14 "Morphine" 15 "Nalbuphine" 16 "Opium" 17 "Oxycodone" 18 "Oxymorphone" 19 "Pentazocine" 20 "Propoxyphene" 21 "Remifentanil" 22 "Tapentadol" 23 "Tramadol"
label values OpioidType OpioidType

replace OpioidType=1 if Drug=="BUNAVAIL 2.1 MG-0.3 MG FIL"
replace OpioidType=1 if Drug=="BUNAVAIL 4.2 MG-0.7 MG FIL"
replace OpioidType=1 if Drug=="BUNAVAIL 6.3 MG-1 MG FIL"
replace OpioidType=1 if Drug=="BUPRENORPHINE  AND NALOXONE 2 MG-0.5 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE  AND NALOXONE 8 MG-2 MG TAB"
replace OpioidType=1 if Drug=="SUBOXONE 12 MG-3 MG FIL"
replace OpioidType=1 if Drug=="SUBOXONE 2 MG-0.5 MG FIL"
replace OpioidType=1 if Drug=="SUBOXONE 4 MG-1 MG FIL"
replace OpioidType=1 if Drug=="SUBOXONE 8 MG-2 MG FIL"
replace OpioidType=1 if Drug=="BUPRENEX 0.3 MG/ML SOL"
replace OpioidType=1 if Drug=="BUPRENORPHINE 0.3 MG/1 ML SOL"
replace OpioidType=1 if Drug=="BUPRENORPHINE 0.3 MG/ML SOL"
replace OpioidType=1 if Drug=="BUTRANS 10 MCG/HR TDM"
replace OpioidType=1 if Drug=="BUTRANS 15 MCG/HR TDM"
replace OpioidType=1 if Drug=="BUTRANS 20 MCG/HR TDM"
replace OpioidType=1 if Drug=="BUTRANS 5 MCG/HR TDM"
replace OpioidType=1 if Drug=="BUTRANS 7.5 MCG/HR TDM"
replace OpioidType=1 if Drug=="BUPRENORPHINE 2 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE 8 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE AND NALOXONE 2 MG-0.5 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE AND NALOXONE 8 MG-2 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE/NALOXON 2 MG-0.5 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE/NALOXON 8 MG-2 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE/NALOXONE 2 MG-0.5 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE/NALOXONE 8 MG-2 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE-NALOXONE 2 MG-0.5 MG TAB"
replace OpioidType=1 if Drug=="BUPRENORPHINE-NALOXONE 8 MG-2 MG TAB"
replace OpioidType=1 if Drug=="SUBOXONE 2 MG-0.5 MG TAB"
replace OpioidType=1 if Drug=="SUBOXONE 8 MG-2 MG TAB"
replace OpioidType=1 if Drug=="SUBUTEX 2 MG TAB"
replace OpioidType=1 if Drug=="SUBUTEX 8 MG TAB"
replace OpioidType=1 if Drug=="ZUBSOLV 1.4 MG-0.36 MG TAB"
replace OpioidType=1 if Drug=="ZUBSOLV 11.4 MG-2.9 MG TAB"
replace OpioidType=1 if Drug=="ZUBSOLV 2.9 MG-0.71 MG TAB"
replace OpioidType=1 if Drug=="ZUBSOLV 5.7 MG-1.4 MG TAB"
replace OpioidType=1 if Drug=="ZUBSOLV 8.6 MG-2.1 MG TAB"
replace OpioidType=2 if Drug=="BUTORPHANOL  NOVAPLUS 2 MG/ML SOL"
replace OpioidType=2 if Drug=="BUTORPHANOL  NOVATION 1 MG/ML SOL"
replace OpioidType=2 if Drug=="BUTORPHANOL 1 MG/ML SOL"
replace OpioidType=2 if Drug=="BUTORPHANOL 10 MG/ML SPR"
replace OpioidType=2 if Drug=="BUTORPHANOL 2 MG/ML SOL"
replace OpioidType=2 if Drug=="STADOL 2 MG/ML SOL"
replace OpioidType=2 if Drug=="STADOL NS 10 MG/ML SPR"
replace OpioidType=3 if Drug=="BUTALBITAL APAP  C 300 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="BUTALBITAL, APAP AND 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="BUTALBITAL, APAP AND CAFFE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="BUTALBITAL,ASA,, AND 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="BUTALBITAL,ASA,, AND CO 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="BUTALBITAL-APAP--C 300 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="BUTALBITAL-APAP--C 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="BUTALBITAL-ASA--CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="ALA-HIST AC 10 MG/5 ML-7.5 MG/5 ML SOL"
replace OpioidType=3 if Drug=="APAP/CODEINE 120 MG/5 ML-12 MG/5 ML ELI"
replace OpioidType=3 if Drug=="APAP/CODEINE 120 MG/5 ML-12 MG/5 ML SOL"
replace OpioidType=3 if Drug=="APAP-CODEINE 120 MG/5 ML-12 MG/5 ML SOL"
replace OpioidType=3 if Drug=="BIOTUSSIN AC 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="BROMPHEN DC/CODEINE  SYR"
replace OpioidType=3 if Drug=="BRONTEX 2.5 MG/5 ML-75 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="CAPITAL/CODEINE 120 MG/5 ML-12 MG/5 ML SUS"
replace OpioidType=3 if Drug=="CHERACOL/CODEINE 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="CHERATUSSIN AC 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="CHERATUSSIN DAC  LIQ"
replace OpioidType=3 if Drug=="CHERATUSSIN DAC  SOL"
replace OpioidType=3 if Drug=="CHLORPHENIRAMINE AND CODEINE 2 MG/5 ML-10 MG/5 ML SOL"
replace OpioidType=3 if Drug=="CODAFED EXPT  SYR"
replace OpioidType=3 if Drug=="CODAFED PED EXPT  SYR"
replace OpioidType=3 if Drug=="CODEINE  GUAIF 10 MG/5 ML-200 MG/5 ML SOL"
replace OpioidType=3 if Drug=="CODEINE 15 MG/5 ML SOL"
replace OpioidType=3 if Drug=="CODEINE 30 MG/5 ML SOL"
replace OpioidType=3 if Drug=="CODEINE 30 MG/ML SOL"
replace OpioidType=3 if Drug=="CODEINE/GUAI 10 MG/5 ML-300 MG/5 ML SOL"
replace OpioidType=3 if Drug=="CODEINE/GUAIF 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="CODEINE/GUAIF/PSEEDRINE  SYR"
replace OpioidType=3 if Drug=="CODEINE/PE/PROMETH  SYR"
replace OpioidType=3 if Drug=="CODEINE/PROMETH 10 MG/5 ML-6.25 MG/5 ML SYR"
replace OpioidType=3 if Drug=="CODEINE-GUAIF 10 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="CODIMAL PH  SYR"
replace OpioidType=3 if Drug=="DEX-TUSS 10 MG/5 ML-300 MG/5 ML SOL"
replace OpioidType=3 if Drug=="DIABETIC TUSSIN C EXPT 10 MG/5 ML-200 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="ENDACOF-C 2 MG/5 ML-10 MG/5 ML SOL"
replace OpioidType=3 if Drug=="GANI-TUSS NR 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="GUAIATUSSIN AC 10 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="GUAI-CO 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="GUAIF AC 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="GUAIF AC 10 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="GUAIF AC 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="GUAIF AC EXPT 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="GUAIF AND CODEINE 10 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="GUAIFEN-C 2.5 MG/5 ML-75 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="GUAITUSSIN AC 10 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="GUIATUSS AC 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="GUIATUSSIN/CODEINE 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="HALOTUSSIN AC 10 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="IOFEN-C NF 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="IOPHEN 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="IOPHEN C-NR 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="IOPHEN-C 10 MG/5 ML-30 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="MAR-COF CG EXPT 7.5 MG/5 ML-225 MG/5 ML SOL"
replace OpioidType=3 if Drug=="M-CLEAR 5 MG/5 ML-350 MG/5 ML SYR"
replace OpioidType=3 if Drug=="M-CLEAR 5 MG/5 ML-400 MG/5 ML SOL"
replace OpioidType=3 if Drug=="M-CLEAR WC 6.33 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="MYTUSSIN AC COUGH 10 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="MYTUSSIN AC COUGH 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="PHENERGAN VC/CODEINE  SYR"
replace OpioidType=3 if Drug=="PHENERGAN/CODEINE 10 MG/5 ML-6.25 MG/5 ML SYR"
replace OpioidType=3 if Drug=="POLY-TUSSIN 9.375 MG/5 ML-10 MG/5 ML SOL"
replace OpioidType=3 if Drug=="PRO-CLEAR AC 9 MG/5 ML-8.33 MG/5 ML SOL"
replace OpioidType=3 if Drug=="PROMETH  AND CODE 10 MG/5 ML-6.25 MG/5 ML SYR"
replace OpioidType=3 if Drug=="PROMETH -CODEINE 10 MG/5 ML-6.25 MG/5 ML SYR"
replace OpioidType=3 if Drug=="PROMETH VC WITH CODEINE  SYR"
replace OpioidType=3 if Drug=="PROMETH VC/CODEINE  SYR"
replace OpioidType=3 if Drug=="PROMETH WITH CODEINE 10 MG/5 ML-6.25 MG/5 ML SYR"
replace OpioidType=3 if Drug=="PROMETH/CODEINE 10 MG/5 ML-6.25 MG/5 ML SYR"
replace OpioidType=3 if Drug=="PROMETH-PE-CODEINE 6.25MG-5MG-10MG/5ML ELI"
replace OpioidType=3 if Drug=="PSEEDRINE AND CODEINE 10 MG/5 ML-30 MG/5 ML SOL"
replace OpioidType=3 if Drug=="ROBAFEN AC 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="ROBAFEN AC COUGH SYRUP 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="ROBITUSSIN-AC 10 MG/5 ML-100 MG/5 ML SYR"
replace OpioidType=3 if Drug=="TUSSIDEN C 10 MG/5 ML-300 MG/5 ML SOL"
replace OpioidType=3 if Drug=="TUSSI-ORGANIDIN 10 MG/5 ML-30 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="TUSSI-ORGANIDIN NR 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="TUSSI-ORGANIDIN NR 10 MG/5 ML-300 MG/5 ML SOL"
replace OpioidType=3 if Drug=="TUSSI-ORGANIDIN-S NR 10 MG/5 ML-100 MG/5 ML LIQ"
replace OpioidType=3 if Drug=="TUSSI-ORGANIDIN-S NR 10 MG/5 ML-300 MG/5 ML SOL"
replace OpioidType=3 if Drug=="TUSSO-C 10 MG/5 ML-200 MG/5 ML SOL"
replace OpioidType=3 if Drug=="TUZISTRA XR 4 MG/5 ML-20 MG/5 ML SER"
replace OpioidType=3 if Drug=="TYLENOL/CODEINE 120 MG/5 ML-12 MG/5 ML ELI"
replace OpioidType=3 if Drug=="VIRTUSSIN A/C 10 MG/5 ML-100 MG/5 ML SOL"
replace OpioidType=3 if Drug=="Z-TUSS AC 2 MG/5 ML-9 MG/5 ML SOL"
replace OpioidType=3 if Drug=="ALLFEN CD 10 MG-400 MG TAB"
replace OpioidType=3 if Drug=="ALLFEN CDX 20 MG-400 MG TAB"
replace OpioidType=3 if Drug=="APAP AND CODEINE 300 MG-15 MG TAB"
replace OpioidType=3 if Drug=="APAP AND CODEINE 300 MG-30 MG TAB"
replace OpioidType=3 if Drug=="APAP AND CODEINE 300 MG-60 MG TAB"
replace OpioidType=3 if Drug=="APAP/ CODEINE 300 MG-30 MG TAB"
replace OpioidType=3 if Drug=="APAP/ CODEINE 300 MG-60 MG TAB"
replace OpioidType=3 if Drug=="APAP/BUTALBITAL/C 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="APAP/CODEINE 300 MG-15 MG TAB"
replace OpioidType=3 if Drug=="APAP/CODEINE 300 MG-30 MG TAB"
replace OpioidType=3 if Drug=="APAP/CODEINE 300 MG-60 MG TAB"
replace OpioidType=3 if Drug=="ASA/BUTALBIT/CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="ASA/CARISOPRODOL/CODEINE 325 MG-200 MG-16 MG TAB"
replace OpioidType=3 if Drug=="ASA/CODEINE 325 MG-30 MG TAB"
replace OpioidType=3 if Drug=="ASA/CODEINE 325 MG-60 MG TAB"
replace OpioidType=3 if Drug=="ASCOMP/CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="BRONTEX 10 MG-300 MG TAB"
replace OpioidType=3 if Drug=="CARISOPRODOL/ASA/CODEINE 325 MG-200 MG-16 MG TAB"
replace OpioidType=3 if Drug=="COCET 650 MG-30 MG TAB"
replace OpioidType=3 if Drug=="CODEINE 15 MG TAB"
replace OpioidType=3 if Drug=="CODEINE 30 MG TAB"
replace OpioidType=3 if Drug=="CODEINE 30 MG TSN"
replace OpioidType=3 if Drug=="CODEINE 60 MG TAB"
replace OpioidType=3 if Drug=="CODEINE 60 MG TSN"
replace OpioidType=3 if Drug=="CODEINE/GUAIF 10 MG-300 MG TAB"
replace OpioidType=3 if Drug=="EMPIRIN/CODEINE 325 MG-30 MG TAB"
replace OpioidType=3 if Drug=="FIORICET WITH CODEIN 300 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="FIORICET WITH CODEIN 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="FIORICET WITH CODEINE 300 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="FIORICET WITH CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="FIORICET/CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="FIORINAL/CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="FIORTAL/CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="MAXIFED CD 10 MG-400 MG-60 MG TAB"
replace OpioidType=3 if Drug=="MAXIFED CDX 20 MG-400 MG-60 MG TAB"
replace OpioidType=3 if Drug=="MAXIFED-G CD 10 MG-400 MG-40 MG TAB"
replace OpioidType=3 if Drug=="MAXIFLU CD 500 MG-10 MG-400 MG-40 MG TAB"
replace OpioidType=3 if Drug=="MAXIPHEN CD 10 MG-400 MG-10 MG TAB"
replace OpioidType=3 if Drug=="MAXIPHEN CDX 20 MG-400 MG-10 MG TAB"
replace OpioidType=3 if Drug=="M-CLEAR 9 MG-200 MG CAP"
replace OpioidType=3 if Drug=="NUCOFED 20 MG-60 MG CAP"
replace OpioidType=3 if Drug=="PHRENILIN WITH  AND CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="PHRENILIN/CODEINE 325 MG-50 MG-40 MG-30 MG CAP"
replace OpioidType=3 if Drug=="PRO-CLEAR CAPS 9 MG-200 MG CAP"
replace OpioidType=3 if Drug=="SOMA CPD/CODEINE 325 MG-200 MG-16 MG TAB"
replace OpioidType=3 if Drug=="TYLENOL WITH CODEINE NO. 3 300 MG-30 MG TAB"
replace OpioidType=3 if Drug=="TYLENOL WITH CODEINE NO. 4 300 MG-60 MG TAB"
replace OpioidType=3 if Drug=="TYLENOL/CODEINE #2 300 MG-15 MG TAB"
replace OpioidType=3 if Drug=="TYLENOL/CODEINE #3 300 MG-30 MG TAB"
replace OpioidType=3 if Drug=="TYLENOL/CODEINE #4 300 MG-60 MG TAB"
replace OpioidType=3 if Drug=="TYLENOL/CODEINE NO 4 300 MG-60 MG TAB"
replace OpioidType=3 if Drug=="VOPAC 650 MG-30 MG TAB"
replace OpioidType=4 if Drug=="DARVOCET A500 500 MG-100 MG TAB"
replace OpioidType=4 if Drug=="DARVOCET-N 100 650 MG-100 MG TAB"
replace OpioidType=4 if Drug=="DARVOCET-N 50 325 MG-50 MG TAB"
replace OpioidType=4 if Drug=="DARVON 65 MG CAP"
replace OpioidType=4 if Drug=="DARVON CPD-65 389 MG-32.4 MG-65 MG CAP"
replace OpioidType=4 if Drug=="DARVON-N 100 MG TAB"
replace OpioidType=4 if Drug=="PROPACET 100 650 MG-100 MG TAB"
replace OpioidType=4 if Drug=="APAP/PROPOXYPHENE 650 MG-65 MG TAB"
replace OpioidType=4 if Drug=="APAP/PROPOXYPHENE N 325 MG-50 MG TAB"
replace OpioidType=4 if Drug=="APAP/PROPOXYPHENE N 650 MG-100 MG TAB"
replace OpioidType=4 if Drug=="ASA/PROPOXYPHENE 389 MG-32.4 MG-65 MG CAP"
replace OpioidType=4 if Drug=="BALACET 325 325 MG-100 MG TAB"
replace OpioidType=4 if Drug=="PROPOXACET-N 650 MG-100 MG TAB"
replace OpioidType=4 if Drug=="PROPOXYPHENE 65 MG CAP"
replace OpioidType=4 if Drug=="PROPOXYPHENE CPD-65 389 MG-32.4 MG-65 MG CAP"
replace OpioidType=4 if Drug=="PROPOXYPHENE N AND ACETAMIN 325 MG-100 MG TAB"
replace OpioidType=4 if Drug=="PROPOXYPHENE N AND ACETAMIN 500 MG-100 MG TAB"
replace OpioidType=4 if Drug=="PROPOXYPHENE N AND ACETAMIN 650 MG-100 MG TAB"
replace OpioidType=4 if Drug=="PROPOXYPHENE N/ACETAMINOPHE 500 MG-100 MG TAB"
replace OpioidType=4 if Drug=="WYGESIC 650 MG-65 MG TAB"
replace OpioidType=5 if Drug=="MOTOFEN 0.025 MG-1 MG TAB"
replace OpioidType=6 if Drug=="DHC PLUS 356.4 MG-30 MG-16 MG CAP"
replace OpioidType=6 if Drug=="APAP--DIHYDROCODEI 320.5 MG-30 MG-16 MG CAP"
replace OpioidType=6 if Drug=="ALAHIST DHC 3 MG/5 ML-7.5 MG/5 ML SOL"
replace OpioidType=6 if Drug=="COLDCOUGH  SOL"
replace OpioidType=6 if Drug=="COLDCOUGH PD  SOL"
replace OpioidType=6 if Drug=="APAP, , AND DIHYDR 712.8 MG-60 MG-32 MG TAB"
replace OpioidType=6 if Drug=="PANLOR DC 356.4 MG-30 MG-16 MG CAP"
replace OpioidType=6 if Drug=="PANLOR SS 712.8 MG-60 MG-32 MG TAB"
replace OpioidType=6 if Drug=="SYNALGOS-DC 356.4 MG-30 MG-16 MG CAP"
replace OpioidType=6 if Drug=="TREZIX 320.5 MG-30 MG-16 MG CAP"
replace OpioidType=6 if Drug=="TREZIX 356.4 MG-30 MG-16 MG CAP"
replace OpioidType=6 if Drug=="ZERLOR 712.8 MG-60 MG-32 MG TAB"
replace OpioidType=7 if Drug=="ATROPINE/DIPHENOXYLATE 0.025 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=7 if Drug=="DIPHENOXYLATE -ATROPINE 0.025 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=7 if Drug=="LOMOTIL 0.025 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=7 if Drug=="ATROP/DIPHENOXYLATE 0.025 MG-2.5 MG TAB"
replace OpioidType=7 if Drug=="ATROPINE/DIPHENOXYLATE 0.025 MG-2.5 MG TAB"
replace OpioidType=7 if Drug=="ATROPINE/DIPHENOXYLATE HYDR 0.025 MG-2.5 MG TAB"
replace OpioidType=7 if Drug=="DIPHENOXYLATE  AND ATR 0.025 MG-2.5 MG TAB"
replace OpioidType=7 if Drug=="DIPHENOXYLATE -ATROPINE 0.025 MG-2.5 MG TAB"
replace OpioidType=7 if Drug=="LOMOTIL 0.025 MG-2.5 MG TAB"
replace OpioidType=7 if Drug=="LONOX 0.025 MG-2.5 MG TAB"
replace OpioidType=8 if Drug=="FENTANYL 0.05 MG/ML SOL"
replace OpioidType=8 if Drug=="FENTANYL 50 MCG/ML SOL"
replace OpioidType=8 if Drug=="SUBLIMAZE 0.05 MG/ML SOL"
replace OpioidType=8 if Drug=="SUBLIMAZE 50 MCG/ML SOL"
replace OpioidType=8 if Drug=="ACTIQ 0.2 MG LOZ"
replace OpioidType=8 if Drug=="ACTIQ 0.4 MG LOZ"
replace OpioidType=8 if Drug=="ACTIQ 0.6 MG LOZ"
replace OpioidType=8 if Drug=="ACTIQ 0.8 MG LOZ"
replace OpioidType=8 if Drug=="ACTIQ 1.2 MG LOZ"
replace OpioidType=8 if Drug=="ACTIQ 1.6 MG LOZ"
replace OpioidType=8 if Drug=="FENTANYL 0.2 MG LOZ"
replace OpioidType=8 if Drug=="FENTANYL 0.4 MG LOZ"
replace OpioidType=8 if Drug=="FENTANYL 0.6 MG LOZ"
replace OpioidType=8 if Drug=="FENTANYL 0.8 MG LOZ"
replace OpioidType=8 if Drug=="FENTANYL 1.2 MG LOZ"
replace OpioidType=8 if Drug=="FENTANYL 1.6 MG LOZ"
replace OpioidType=8 if Drug=="ORAL TRANSMUCOSAL FENTANYL 0.2 MG LOZ"
replace OpioidType=8 if Drug=="ORAL TRANSMUCOSAL FENTANYL 0.4 MG LOZ"
replace OpioidType=8 if Drug=="ORAL TRANSMUCOSAL FENTANYL 0.6 MG LOZ"
replace OpioidType=8 if Drug=="ORAL TRANSMUCOSAL FENTANYL 0.8 MG LOZ"
replace OpioidType=8 if Drug=="ORAL TRANSMUCOSAL FENTANYL 1.2 MG LOZ"
replace OpioidType=8 if Drug=="ORAL TRANSMUCOSAL FENTANYL 1.6 MG LOZ"
replace OpioidType=8 if Drug=="LAZANDA 100 MCG/Spray SPR"
replace OpioidType=8 if Drug=="LAZANDA 400 MCG/Spray SPR"
replace OpioidType=8 if Drug=="SUBSYS 100 MCG/Spray SPR"
replace OpioidType=8 if Drug=="SUBSYS 1200 MCG/Spray SPR"
replace OpioidType=8 if Drug=="SUBSYS 1600 MCG/Spray SPR"
replace OpioidType=8 if Drug=="SUBSYS 200 MCG/Spray SPR"
replace OpioidType=8 if Drug=="SUBSYS 400 MCG/Spray SPR"
replace OpioidType=8 if Drug=="SUBSYS 600 MCG/Spray SPR"
replace OpioidType=8 if Drug=="SUBSYS 800 MCG/Spray SPR"
replace OpioidType=8 if Drug=="DURAGESIC 100 MCG/HR TDM"
replace OpioidType=8 if Drug=="DURAGESIC 12 MCG/HR TDM"
replace OpioidType=8 if Drug=="DURAGESIC 25 MCG/HR TDM"
replace OpioidType=8 if Drug=="DURAGESIC 50 MCG/HR TDM"
replace OpioidType=8 if Drug=="DURAGESIC 75 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL 100 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL 12 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL 25 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL 37.5 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL 50 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL 62.5 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL 75 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL 87.5 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL TRANSDERMAL SYSTEM 100 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL TRANSDERMAL SYSTEM 12 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL TRANSDERMAL SYSTEM 25 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL TRANSDERMAL SYSTEM 50 MCG/HR TDM"
replace OpioidType=8 if Drug=="FENTANYL TRANSDERMAL SYSTEM 75 MCG/HR TDM"
replace OpioidType=8 if Drug=="NOVAPLUS FENTANYL 100 MCG/HR TDM"
replace OpioidType=8 if Drug=="NOVAPLUS FENTANYL 25 MCG/HR TDM"
replace OpioidType=8 if Drug=="NOVAPLUS FENTANYL 50 MCG/HR TDM"
replace OpioidType=8 if Drug=="NOVAPLUS FENTANYL 75 MCG/HR TDM"
replace OpioidType=8 if Drug=="NOVAPLUS FENTANYL TRANSDERMAL SYSTE 100 MCG/HR TDM"
replace OpioidType=8 if Drug=="NOVAPLUS FENTANYL TRANSDERMAL SYSTE 25 MCG/HR TDM"
replace OpioidType=8 if Drug=="NOVAPLUS FENTANYL TRANSDERMAL SYSTE 50 MCG/HR TDM"
replace OpioidType=8 if Drug=="NOVAPLUS FENTANYL TRANSDERMAL SYSTE 75 MCG/HR TDM"
replace OpioidType=8 if Drug=="ABSTRAL 100 MCG TAB"
replace OpioidType=8 if Drug=="ABSTRAL 200 MCG TAB"
replace OpioidType=8 if Drug=="ABSTRAL 400 MCG TAB"
replace OpioidType=8 if Drug=="ABSTRAL 600 MCG TAB"
replace OpioidType=8 if Drug=="ABSTRAL 800 MCG TAB"
replace OpioidType=8 if Drug=="FENTORA 100 MCG TAB"
replace OpioidType=8 if Drug=="FENTORA 200 MCG TAB"
replace OpioidType=8 if Drug=="FENTORA 300 MCG TAB"
replace OpioidType=8 if Drug=="FENTORA 400 MCG TAB"
replace OpioidType=8 if Drug=="FENTORA 600 MCG TAB"
replace OpioidType=8 if Drug=="FENTORA 800 MCG TAB"
replace OpioidType=9 if Drug=="ATUSS HD 2 MG-5 MG-30 MG CAP"
replace OpioidType=9 if Drug=="ATUSS HX 300 MG-5 MG CAP"
replace OpioidType=9 if Drug=="A-COF DH 300 MG/5 ML-3.5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="ANAPLEX HD  SYR"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 500 MG/15 ML-7.5 MG/15 ML ELI"
replace OpioidType=9 if Drug=="ATUSS HC  SYR"
replace OpioidType=9 if Drug=="ATUSS HS  SUS"
replace OpioidType=9 if Drug=="ATUSS NX 3 MG/5 ML-150 MG/5 ML SOL"
replace OpioidType=9 if Drug=="BROMCOMP HC  SOL"
replace OpioidType=9 if Drug=="BROMPLEX HD  SOL"
replace OpioidType=9 if Drug=="BROVEX HC  SOL"
replace OpioidType=9 if Drug=="B-TUSS  LIQ"
replace OpioidType=9 if Drug=="CLEARTUSS DH 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="CODAL-DH  SYR"
replace OpioidType=9 if Drug=="CODAMINE 5 MG/5 ML-25 MG/5 ML SYR"
replace OpioidType=9 if Drug=="CODICLEAR DH 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="CODICLEAR DH 300 MG/5 ML-3.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="CODIMAL DH  SYR"
replace OpioidType=9 if Drug=="CODITUSS DH  SYR"
replace OpioidType=9 if Drug=="COLDCOUGH HC  SYR"
replace OpioidType=9 if Drug=="COLDCOUGH HCM 3 MG/5 ML-15 MG/5 ML SOL"
replace OpioidType=9 if Drug=="COMTUSSIN HC  SYR"
replace OpioidType=9 if Drug=="COTUSS-V 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="COUGHTUSS  SOL"
replace OpioidType=9 if Drug=="CPM/HYDROCODONE/PE  SOL"
replace OpioidType=9 if Drug=="CRANTEX HC  SYR"
replace OpioidType=9 if Drug=="CYTUSS HC  SYR"
replace OpioidType=9 if Drug=="CYTUSS-HC NR  SOL"
replace OpioidType=9 if Drug=="DE-CHLOR HC  SOL"
replace OpioidType=9 if Drug=="DE-CHLOR HD  SYR"
replace OpioidType=9 if Drug=="D-TANN HC  SUS"
replace OpioidType=9 if Drug=="ENDACOF XP 200 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="FLOWTUSS 200MG-2.5MG/5ML SOL"
replace OpioidType=9 if Drug=="GUAIF/HYDROCODONE BI 100 MG/5 ML-5 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="GUAIF/HYDROCODONE BI 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="H-C TUSSIVE-D 5 MG/5 ML-60 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HC/GUAI 300 MG/5 ML-3.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="HISTUSSIN-D 5 MG/5 ML-60 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="HOMATROP/HYDROCODONE 1.5 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HOMATROPINE METHYLBROMIDE/HYDROCODO 1.5 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYCET 325 MG/15 ML-7.5 MG/15 ML ELI"
replace OpioidType=9 if Drug=="HYCODAN 1.5 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYCOFENIX 200MG-2.5MG-30MG/5ML SOL"
replace OpioidType=9 if Drug=="HYCOSIN EXPT 100 MG/5 ML-5 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="HYCOTUSS EXPT 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDROCODONE AND CHLORPHENIRAMINE PE 8 MG/5 ML-10 MG/5 ML SER"
replace OpioidType=9 if Drug=="HYDROCODONE AND CHLORPHENIRAMINE PO 8 MG/5 ML-10 MG/5 ML SER"
replace OpioidType=9 if Drug=="HYDROCODONE BI & HOMATROPIN 1.5 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 108 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 163 MG/7.5 ML-5 MG/7.5 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 167 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 217 MG/10 ML-5 MG/10 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 325 MG/15 ML-10 MG/15 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 325 MG/15 ML-7.5 MG/15 ML ELI"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 325 MG/15 ML-7.5 MG/15 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI/GUAIF 100 MG/5 ML-5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 108 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 163 MG/7.5 ML-5 MG/7.5 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 167 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 217 MG/10 ML-5 MG/10 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 325 MG/15 ML-10 MG/15 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 325 MG/15 ML-7.5 MG/15 ML ELI"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 325 MG/15 ML-7.5 MG/15 ML SOL"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 500 MG/15 ML-7.5 MG/15 ML ELI"
replace OpioidType=9 if Drug=="HYDROCODONE BI-HOMATROPINE 1.5 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDROCODONE CPD 1.5 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDROCODONE GF 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDROCODONE PA 5 MG/5 ML-25 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDROCODONE POLISTIREX/CHLORPHENIRA 8 MG/5 ML-10 MG/5 ML SER"
replace OpioidType=9 if Drug=="HYDROCODONE POLISTIREX-CHLORPHENIRA 8 MG/5 ML-10 MG/5 ML SER"
replace OpioidType=9 if Drug=="HYDROCODONE/POT GUAI 4.5 MG/5 ML-300 MG/5 ML SOL"
replace OpioidType=9 if Drug=="HYDROMET 1.5 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDRON EX 2.5 MG/5 ML-120 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDRON KGS 5 MG/5 ML-300 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="HYDROTROPINE 1.5 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HYDROTUSS 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="HY-KXP 4.5 MG/5 ML-300 MG/5 ML SOL"
replace OpioidType=9 if Drug=="KWELCOF 100 MG/5 ML-5 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="LEVALL 5.0  LIQ"
replace OpioidType=9 if Drug=="LEVALL 5.0  SOL"
replace OpioidType=9 if Drug=="LORTAB ELIXIR 300 MG/15 ML-10 MG/15 ML ELI"
replace OpioidType=9 if Drug=="NALEX DH 2.5 MG/5 ML-5 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="OBREDON 200 MG/5 ML-2.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="PANCOF HC 3 MG/5 ML-15 MG/5 ML SOL"
replace OpioidType=9 if Drug=="PNEUMOTUSSIN 2.5 200 MG/5 ML-2.5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="PROLEX DH 4.5 MG/5 ML-300 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="PROTUSS 5 MG/5 ML-300 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="REZIRA 5 MG/5 ML-60 MG/5 ML SYR"
replace OpioidType=9 if Drug=="SYMTAN 10 MG/5 ML-45 MG/5 ML SOL"
replace OpioidType=9 if Drug=="TUSDEC-HC 3.75 MG/5 ML-7.5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="TUSSIONEX C 8 MG/5 ML-10 MG/5 ML SER"
replace OpioidType=9 if Drug=="VICOCLEAR 100 MG/5 ML-5 MG/5 ML LIQ"
replace OpioidType=9 if Drug=="VICODIN TUSS EXPT 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="VI-Q-TUSS 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="VITUSSIN EXPT 100 MG/5 ML-5 MG/5 ML SYR"
replace OpioidType=9 if Drug=="VITUZ 4 MG/5 ML-5 MG/5 ML SOL"
replace OpioidType=9 if Drug=="ZAMICET 325 MG/15 ML-10 MG/15 ML SOL"
replace OpioidType=9 if Drug=="ZOLVIT 300 MG/15 ML-10 MG/15 ML ELI"
replace OpioidType=9 if Drug=="ZUTRIPRO  SYR"
replace OpioidType=9 if Drug=="ANEXSIA 325 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="ANEXSIA 650 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="APAP & HYDROCODONE 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE 750 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 325 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 500 MG-2.5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 500 MG-5 MG CAP"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 500 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 650 MG-10 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 650 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 660 MG-10 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 750 MG-10 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI 750 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="APAP/HYDROCODONE BI HS 500 MG-2.5 MG TAB"
replace OpioidType=9 if Drug=="APAP-HYDROCODONE 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="APAP-HYDROCODONE 325 MG-2.5 MG TAB"
replace OpioidType=9 if Drug=="APAP-HYDROCODONE 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="CO-GESIC 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="ENDACOF 300 MG-2.5 MG TAB"
replace OpioidType=9 if Drug=="EXTENDRYL HC 1000 MG-10 MG TER"
replace OpioidType=9 if Drug=="HOMATROP/HYDROCODONE 1.5 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYCODAN 1.5 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCET 500 MG-5 MG CAP"
replace OpioidType=9 if Drug=="HYDROCODONE BI & ACETAMINOP 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 300 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 300 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 300 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 325 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 500 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 650 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 650 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 660 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 750 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND ACETAMIN 750 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND HOMATROP 1.5 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND IBUPROFE 10 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND IBUPROFE 2.5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND IBUPROFE 5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI AND IBUPROFE 7.5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/ACETAMINOPHE 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/ACETAMINOPHE 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/ACETAMINOPHE 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/ACETAMINOPHE 500 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/APAP 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/APAP 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/APAP 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/APAP 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/APAP 650 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/APAP 750 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI/IBUPROFEN 7.5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 300 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 300 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 300 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 325 MG-2.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 325 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 500 MG-2.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 500 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 650 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 650 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 660 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 750 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-ACETAMINOPHE 750 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-HOMATROPINE 1.5 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-IBUPROFEN 10 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-IBUPROFEN 2.5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-IBUPROFEN 5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BI-IBUPROFEN 7.5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BITART/ACET 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BITART/ACET 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE BITART/ACET 750 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE/APAP 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE/APAP 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE/APAP 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE/APAP 500 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE/APAP 650 MG-10 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE/APAP 750 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="HYDROCODONE/HOMATROPINE 1.5 MG-5 MG TAB"
replace OpioidType=9 if Drug=="HYSINGLA ER 100 MG TER"
replace OpioidType=9 if Drug=="HYSINGLA ER 120 MG TER"
replace OpioidType=9 if Drug=="HYSINGLA ER 20 MG TER"
replace OpioidType=9 if Drug=="HYSINGLA ER 30 MG TER"
replace OpioidType=9 if Drug=="HYSINGLA ER 40 MG TER"
replace OpioidType=9 if Drug=="HYSINGLA ER 60 MG TER"
replace OpioidType=9 if Drug=="HYSINGLA ER 80 MG TER"
replace OpioidType=9 if Drug=="IBUDONE 10 MG-200 MG TAB"
replace OpioidType=9 if Drug=="IBUDONE 5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="LORCET 10/650 650 MG-10 MG TAB"
replace OpioidType=9 if Drug=="LORCET 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="LORCET HD 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="LORCET PLUS 325 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="LORCET PLUS 650 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="LORCET-HD 500 MG-5 MG CAP"
replace OpioidType=9 if Drug=="LORTAB 10/325 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="LORTAB 10/500 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="LORTAB 2.5/500 500 MG-2.5 MG TAB"
replace OpioidType=9 if Drug=="LORTAB 5/325 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="LORTAB 5/500 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="LORTAB 500 MG/15 ML-7.5 MG/15 ML ELI"
replace OpioidType=9 if Drug=="LORTAB 500 MG-10 MG TAB"
replace OpioidType=9 if Drug=="LORTAB 7.5/325 325 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="LORTAB 7.5/500 500 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="MAXIDONE 750 MG-10 MG TAB"
replace OpioidType=9 if Drug=="NORCO 325 MG-10 MG TAB"
replace OpioidType=9 if Drug=="NORCO 325 MG-5 MG TAB"
replace OpioidType=9 if Drug=="NORCO 325 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="POLYGESIC 500 MG-5 MG CAP"
replace OpioidType=9 if Drug=="REPREXAIN 10 MG-200 MG TAB"
replace OpioidType=9 if Drug=="REPREXAIN 2.5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="REPREXAIN 5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="REPREXAIN 7.5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="STAGESIC 500 MG-5 MG CAP"
replace OpioidType=9 if Drug=="TUSSEND 4 MG-5 MG-60 MG TAB"
replace OpioidType=9 if Drug=="TUSSICAPS 4 MG-5 MG CER"
replace OpioidType=9 if Drug=="TUSSICAPS 8 MG-10 MG CER"
replace OpioidType=9 if Drug=="TUSSIGON 1.5 MG-5 MG TAB"
replace OpioidType=9 if Drug=="VICODIN 300 MG-5 MG TAB"
replace OpioidType=9 if Drug=="VICODIN 500 MG-5 MG TAB"
replace OpioidType=9 if Drug=="VICODIN ES 300 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="VICODIN ES 750 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="VICODIN HP 300 MG-10 MG TAB"
replace OpioidType=9 if Drug=="VICODIN HP 660 MG-10 MG TAB"
replace OpioidType=9 if Drug=="VICOPROFEN 7.5 MG-200 MG TAB"
replace OpioidType=9 if Drug=="XODOL 300 MG-10 MG TAB"
replace OpioidType=9 if Drug=="XODOL 5/300 300 MG-5 MG TAB"
replace OpioidType=9 if Drug=="XODOL 7.5/300 300 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="XPECT-HC 600 MG-5 MG TER"
replace OpioidType=9 if Drug=="XYLON 10 10 MG-200 MG TAB"
replace OpioidType=9 if Drug=="ZOHYDRO ER 10 MG CER"
replace OpioidType=9 if Drug=="ZOHYDRO ER 15 MG CER"
replace OpioidType=9 if Drug=="ZOHYDRO ER 20 MG CER"
replace OpioidType=9 if Drug=="ZOHYDRO ER 30 MG CER"
replace OpioidType=9 if Drug=="ZOHYDRO ER 40 MG CER"
replace OpioidType=9 if Drug=="ZOHYDRO ER 50 MG CER"
replace OpioidType=9 if Drug=="ZTUSS 300 MG-5 MG-30 MG TAB"
replace OpioidType=9 if Drug=="ZYDONE 400 MG-10 MG TAB"
replace OpioidType=9 if Drug=="ZYDONE 400 MG-5 MG TAB"
replace OpioidType=9 if Drug=="ZYDONE 400 MG-7.5 MG TAB"
replace OpioidType=9 if Drug=="CARB/HYDROCODONE/PSE  SOL"
replace OpioidType=10 if Drug=="DILAUDID 1 MG/ML SOL"
replace OpioidType=10 if Drug=="DILAUDID 2 MG/ML SOL"
replace OpioidType=10 if Drug=="DILAUDID 4 MG/ML SOL"
replace OpioidType=10 if Drug=="DILAUDID 3 MG SUP"
replace OpioidType=10 if Drug=="DILAUDID COUGH 100 MG/5 ML-1 MG/5 ML SYR"
replace OpioidType=10 if Drug=="DILAUDID-5 1 MG/ML LIQ"
replace OpioidType=10 if Drug=="DILAUDID-HP 10 MG/ML SOL"
replace OpioidType=10 if Drug=="HYDROMORPHONE 1 MG/ML LIQ"
replace OpioidType=10 if Drug=="HYDROMORPHONE 1 MG/ML SOL"
replace OpioidType=10 if Drug=="HYDROMORPHONE 10 MG/ML SOL"
replace OpioidType=10 if Drug=="HYDROMORPHONE 2 MG/ML SOL"
replace OpioidType=10 if Drug=="HYDROMORPHONE 3 MG SUP"
replace OpioidType=10 if Drug=="HYDROMORPHONE 4 MG/ML SOL"
replace OpioidType=10 if Drug=="HYDROMORPHONE HYDROCHLORIDE 1 MG/ML SOL"
replace OpioidType=10 if Drug=="HYDROMORPHONE/NACL 1 MG/5 ML-0.9% SOL"
replace OpioidType=10 if Drug=="HYDROMORPHONE/NACL 10 MG/50 ML-0.9% SOL"
replace OpioidType=10 if Drug=="DILAUDID 2 MG TAB"
replace OpioidType=10 if Drug=="DILAUDID 4 MG TAB"
replace OpioidType=10 if Drug=="DILAUDID 8 MG TAB"
replace OpioidType=10 if Drug=="EXALGO 12 MG TER"
replace OpioidType=10 if Drug=="EXALGO 16 MG TER"
replace OpioidType=10 if Drug=="EXALGO 32 MG TER"
replace OpioidType=10 if Drug=="EXALGO 8 MG TER"
replace OpioidType=10 if Drug=="HYDROMORPHONE 12 MG TER"
replace OpioidType=10 if Drug=="HYDROMORPHONE 16 MG TER"
replace OpioidType=10 if Drug=="HYDROMORPHONE 2 MG TAB"
replace OpioidType=10 if Drug=="HYDROMORPHONE 32 MG TER"
replace OpioidType=10 if Drug=="HYDROMORPHONE 4 MG TAB"
replace OpioidType=10 if Drug=="HYDROMORPHONE 8 MG TAB"
replace OpioidType=10 if Drug=="HYDROMORPHONE 8 MG TER"
replace OpioidType=11 if Drug=="LEVO-DROMORAN 2 MG TAB"
replace OpioidType=11 if Drug=="LEVORPHANOL 2 MG TAB"
replace OpioidType=12 if Drug=="DEMEROL 100 MG/ML SOL"
replace OpioidType=12 if Drug=="DEMEROL 25 MG/ML SOL"
replace OpioidType=12 if Drug=="DEMEROL 50 MG TAB"
replace OpioidType=12 if Drug=="DEMEROL 50 MG/5 ML SYR"
replace OpioidType=12 if Drug=="DEMEROL 50 MG/ML SOL"
replace OpioidType=12 if Drug=="DEMEROL 75 MG/ML SOL"
replace OpioidType=12 if Drug=="DEMEROL 100 MG TAB"
replace OpioidType=12 if Drug=="MEPROZINE 50 MG-25 MG CAP"
replace OpioidType=13 if Drug=="METHADONE  CONCENTRATE 10 MG/ML SOL"
replace OpioidType=13 if Drug=="METHADONE  INTENSOL 10 MG/ML SOL"
replace OpioidType=13 if Drug=="METHADONE 10 MG/5 ML SOL"
replace OpioidType=13 if Drug=="METHADONE 10 MG/ML SOL"
replace OpioidType=13 if Drug=="METHADONE 5 MG/5 ML SOL"
replace OpioidType=13 if Drug=="METHADOSE 10 MG/ML SOL"
replace OpioidType=13 if Drug=="DISKETS DISPERSIBLE 40 MG TAB"
replace OpioidType=13 if Drug=="DOLOPHINE 10 MG TAB"
replace OpioidType=13 if Drug=="DOLOPHINE 5 MG TAB"
replace OpioidType=13 if Drug=="METHADONE 10 MG TAB"
replace OpioidType=13 if Drug=="METHADONE 40 MG TAB"
replace OpioidType=13 if Drug=="METHADONE 40 MG TBS"
replace OpioidType=13 if Drug=="METHADONE 5 MG TAB"
replace OpioidType=13 if Drug=="METHADOSE 10 MG TAB"
replace OpioidType=13 if Drug=="METHADOSE 40 MG TAB"
replace OpioidType=13 if Drug=="METHADOSE 5 MG TAB"
replace OpioidType=14 if Drug=="AVINZA 120 MG C24"
replace OpioidType=14 if Drug=="AVINZA 30 MG C24"
replace OpioidType=14 if Drug=="AVINZA 45 MG C24"
replace OpioidType=14 if Drug=="AVINZA 60 MG C24"
replace OpioidType=14 if Drug=="AVINZA 75 MG C24"
replace OpioidType=14 if Drug=="AVINZA 90 MG C24"
replace OpioidType=14 if Drug=="EMBEDA 100 MG-4 MG CER"
replace OpioidType=14 if Drug=="EMBEDA 20 MG-0.8 MG CER"
replace OpioidType=14 if Drug=="EMBEDA 30 MG-1.2 MG CER"
replace OpioidType=14 if Drug=="EMBEDA 50 MG-2 MG CER"
replace OpioidType=14 if Drug=="EMBEDA 60 MG-2.4 MG CER"
replace OpioidType=14 if Drug=="EMBEDA 80 MG-3.2 MG CER"
replace OpioidType=12 if Drug=="MEPERIDINE 10 MG/ML SOL"
replace OpioidType=12 if Drug=="MEPERIDINE 100 MG/ML SOL"
replace OpioidType=12 if Drug=="MEPERIDINE 25 MG/ML SOL"
replace OpioidType=12 if Drug=="MEPERIDINE 50 MG/5 ML SOL"
replace OpioidType=12 if Drug=="MEPERIDINE 50 MG/ML SOL"
replace OpioidType=12 if Drug=="MEPERIDINE 75 MG/ML SOL"
replace OpioidType=14 if Drug=="ASTRAMORPH/PF 0.5 MG/ML SOL"
replace OpioidType=14 if Drug=="ASTRAMORPH/PF 1 MG/ML SOL"
replace OpioidType=14 if Drug=="DURAMORPH 0.5 MG/ML SOL"
replace OpioidType=14 if Drug=="DURAMORPH 1 MG/ML SOL"
replace OpioidType=14 if Drug=="INFUMORPH 200 10 MG/ML SOL"
replace OpioidType=14 if Drug=="INFUMORPH 25 MG/ML SOL"
replace OpioidType=14 if Drug=="INFUMORPH 500 25 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 0.5 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 1 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 10 MG/0.5 ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 10 MG/1 ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 10 MG/5 ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 10 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 15 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 2 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 20 MG/1 ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 20 MG/5 ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 20 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 25 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 4 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 5 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 50 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 8 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE-NACL 0.5 MG/0.5 ML-0.9% SOL"
replace OpioidType=14 if Drug=="MSIR 20 MG/ML SOL"
replace OpioidType=14 if Drug=="PAREGORIC 2 MG/5 ML LIQ"
replace OpioidType=14 if Drug=="ROXANOL 20 MG/ML SOL"
replace OpioidType=14 if Drug=="ROXANOL-T 20 MG/ML SOL"
replace OpioidType=14 if Drug=="MORPHINE 10 MG SUP"
replace OpioidType=14 if Drug=="MORPHINE 30 MG SUP"
replace OpioidType=14 if Drug=="MORPHINE 5 MG SUP"
replace OpioidType=14 if Drug=="RMS 10 MG SUP"
replace OpioidType=14 if Drug=="RMS 20 MG SUP"
replace OpioidType=14 if Drug=="RMS 30 MG SUP"
replace OpioidType=14 if Drug=="RMS 5 MG SUP"
replace OpioidType=12 if Drug=="MEPERIDINE 100 MG TAB"
replace OpioidType=12 if Drug=="MEPERIDINE 50 MG TAB"
replace OpioidType=12 if Drug=="MEPERIDINE/PROMETH 50 MG-25 MG CAP"
replace OpioidType=12 if Drug=="MEPERIDINE-PROMETH 50 MG-25 MG CAP"
replace OpioidType=12 if Drug=="MEPERITAB 100 MG TAB"
replace OpioidType=12 if Drug=="MEPERITAB 50 MG TAB"
replace OpioidType=14 if Drug=="KADIAN 10 MG CER"
replace OpioidType=14 if Drug=="KADIAN 100 MG CER"
replace OpioidType=14 if Drug=="KADIAN 130 MG CER"
replace OpioidType=14 if Drug=="KADIAN 150 MG CER"
replace OpioidType=14 if Drug=="KADIAN 20 MG CER"
replace OpioidType=14 if Drug=="KADIAN 200 MG CER"
replace OpioidType=14 if Drug=="KADIAN 30 MG CER"
replace OpioidType=14 if Drug=="KADIAN 40 MG CER"
replace OpioidType=14 if Drug=="KADIAN 50 MG CER"
replace OpioidType=14 if Drug=="KADIAN 60 MG CER"
replace OpioidType=14 if Drug=="KADIAN 70 MG CER"
replace OpioidType=14 if Drug=="KADIAN 80 MG CER"
replace OpioidType=14 if Drug=="MORPHINE  CONTR REL 100 MG TER"
replace OpioidType=14 if Drug=="MORPHINE 10 MG CER"
replace OpioidType=14 if Drug=="MORPHINE 10 MG TAB"
replace OpioidType=14 if Drug=="MORPHINE 100 MG CER"
replace OpioidType=14 if Drug=="MORPHINE 100 MG TER"
replace OpioidType=14 if Drug=="MORPHINE 120 MG C24"
replace OpioidType=14 if Drug=="MORPHINE 15 MG TAB"
replace OpioidType=14 if Drug=="MORPHINE 15 MG TER"
replace OpioidType=14 if Drug=="MORPHINE 20 MG CER"
replace OpioidType=14 if Drug=="MORPHINE 20 MG SUP"
replace OpioidType=14 if Drug=="MORPHINE 200 MG TER"
replace OpioidType=14 if Drug=="MORPHINE 30 MG C24"
replace OpioidType=14 if Drug=="MORPHINE 30 MG CER"
replace OpioidType=14 if Drug=="MORPHINE 30 MG TAB"
replace OpioidType=14 if Drug=="MORPHINE 30 MG TER"
replace OpioidType=14 if Drug=="MORPHINE 45 MG C24"
replace OpioidType=14 if Drug=="MORPHINE 50 MG CER"
replace OpioidType=14 if Drug=="MORPHINE 60 MG C24"
replace OpioidType=14 if Drug=="MORPHINE 60 MG CER"
replace OpioidType=14 if Drug=="MORPHINE 60 MG TER"
replace OpioidType=14 if Drug=="MORPHINE 75 MG C24"
replace OpioidType=14 if Drug=="MORPHINE 80 MG CER"
replace OpioidType=14 if Drug=="MORPHINE 90 MG C24"
replace OpioidType=14 if Drug=="MS CONTIN 100 MG TER"
replace OpioidType=14 if Drug=="MS CONTIN 15 MG TER"
replace OpioidType=14 if Drug=="MS CONTIN 200 MG TER"
replace OpioidType=14 if Drug=="MS CONTIN 30 MG TER"
replace OpioidType=14 if Drug=="MS CONTIN 60 MG TER"
replace OpioidType=14 if Drug=="MSIR 15 MG CAP"
replace OpioidType=14 if Drug=="MSIR 15 MG TAB"
replace OpioidType=14 if Drug=="MSIR 30 MG TAB"
replace OpioidType=14 if Drug=="ORAMORPH SR 100 MG TER"
replace OpioidType=14 if Drug=="ORAMORPH SR 15 MG TER"
replace OpioidType=14 if Drug=="ORAMORPH SR 30 MG TER"
replace OpioidType=14 if Drug=="ORAMORPH SR 60 MG TER"
replace OpioidType=15 if Drug=="NALBUPHINE 10 MG/ML SOL"
replace OpioidType=15 if Drug=="NALBUPHINE 20 MG/ML SOL"
replace OpioidType=15 if Drug=="NOVAPLUS NALBUPHINE 10 MG/ML SOL"
replace OpioidType=15 if Drug=="NOVAPLUS NALBUPHINE 20 MG/ML SOL"
replace OpioidType=16 if Drug=="OPIUM 10 MG/ML TIN"
replace OpioidType=16 if Drug=="OPIUM 10% TIN"
replace OpioidType=16 if Drug=="OPIUM TINCTURE 2 MG/5 ML LIQ"
replace OpioidType=16 if Drug=="B & O SUPPRETTES 15A 16.2 MG-30 MG SUP"
replace OpioidType=16 if Drug=="B & O SUPPRETTES 16A 16.2 MG-60 MG SUP"
replace OpioidType=16 if Drug=="BELLADONNA/OPIUM 15 MG-60 MG SUP"
replace OpioidType=16 if Drug=="BELLADONNA/OPIUM 16.2 MG-30 MG SUP"
replace OpioidType=16 if Drug=="BELLADONNA/OPIUM 16.2 MG-60 MG SUP"
replace OpioidType=17 if Drug=="ETH-OXYDOSE 20 MG/ML SOL"
replace OpioidType=17 if Drug=="OXYCODONE 20 MG/1 ML SOL"
replace OpioidType=17 if Drug=="OXYCODONE 20 MG/ML SOL"
replace OpioidType=17 if Drug=="OXYCODONE 5 MG/5 ML SOL"
replace OpioidType=17 if Drug=="OXYFAST 20 MG/ML SOL"
replace OpioidType=17 if Drug=="ROXICET 325 MG/5 ML-5 MG/5 ML SOL"
replace OpioidType=17 if Drug=="ROXICODONE 20 MG/ML SOL"
replace OpioidType=17 if Drug=="ROXICODONE 5 MG/5 ML SOL"
replace OpioidType=17 if Drug=="ROXICODONE INTENSOL 20 MG/ML SOL"
replace OpioidType=17 if Drug=="APAP/OXYCODONE 325 MG-10 MG TAB"
replace OpioidType=17 if Drug=="APAP/OXYCODONE 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="APAP/OXYCODONE 325 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="APAP/OXYCODONE 500 MG-5 MG CAP"
replace OpioidType=17 if Drug=="APAP/OXYCODONE 500 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="APAP/OXYCODONE 650 MG-10 MG TAB"
replace OpioidType=17 if Drug=="APAP/OXYCODONE HYDROCHLORI 325 MG-10 MG TAB"
replace OpioidType=17 if Drug=="APAP-OXYCODONE 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="ASA/OXYCODONE 325 MG-4.5 MG-0.38 MG TAB"
replace OpioidType=17 if Drug=="COMBUNOX 400 MG-5 MG TAB"
replace OpioidType=17 if Drug=="ENDOCET 325 MG-10 MG TAB"
replace OpioidType=17 if Drug=="ENDOCET 325 MG-2.5 MG TAB"
replace OpioidType=17 if Drug=="ENDOCET 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="ENDOCET 325 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="ENDOCET 500 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="ENDOCET 650 MG-10 MG TAB"
replace OpioidType=17 if Drug=="ENDODAN 325 MG-4.5 MG-0.38 MG TAB"
replace OpioidType=17 if Drug=="ENDODAN 325 MG-4.8355 MG TAB"
replace OpioidType=17 if Drug=="MAGNACET 400 MG-10 MG TAB"
replace OpioidType=17 if Drug=="MAGNACET 400 MG-2.5 MG TAB"
replace OpioidType=17 if Drug=="MAGNACET 400 MG-5 MG TAB"
replace OpioidType=17 if Drug=="MAGNACET 400 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="NARVOX 500 MG-10 MG TAB"
replace OpioidType=17 if Drug=="OXAYDO 5 MG TAB"
replace OpioidType=17 if Drug=="OXAYDO 7.5 MG TAB"
replace OpioidType=17 if Drug=="OXECTA 5 MG TAB"
replace OpioidType=17 if Drug=="OXECTA 7.5 MG TAB"
replace OpioidType=17 if Drug=="OXY IR 5 MG CAP"
replace OpioidType=17 if Drug=="OXYCODONE  AND APAP 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE  AND IBUPROF 400 MG-5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE 10 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE 10 MG TER"
replace OpioidType=17 if Drug=="OXYCODONE 15 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE 20 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE 20 MG TER"
replace OpioidType=17 if Drug=="OXYCODONE 30 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE 40 MG TER"
replace OpioidType=17 if Drug=="OXYCODONE 5 MG CAP"
replace OpioidType=17 if Drug=="OXYCODONE 5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE 80 MG TER"
replace OpioidType=17 if Drug=="OXYCODONE AND APAP 325 MG-10 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE AND APAP 325 MG-2.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE AND APAP 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE AND APAP 325 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE AND APAP 500 MG-5 MG CAP"
replace OpioidType=17 if Drug=="OXYCODONE AND APAP 500 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE AND APAP 650 MG-10 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE AND ASA 325 MG-4.8355 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE -APAP 325 MG-10 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE -APAP 325 MG-2.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE -APAP 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE -APAP 325 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE -ASA 325 MG-4.8355 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE CR 10 MG TER"
replace OpioidType=17 if Drug=="OXYCODONE -IBUPROFEN 400 MG-5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE/ACETAMINOPH 325 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE/APAP 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE/APAP 325 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE-APAP 325 MG-10 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE-APAP 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE-APAP 325 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE-APAP 500 MG-5 MG CAP"
replace OpioidType=17 if Drug=="OXYCODONE-APAP 500 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE-APAP 650 MG-10 MG TAB"
replace OpioidType=17 if Drug=="OXYCODONE-ASA 325 MG-4.5 MG-0.38 MG TAB"
replace OpioidType=17 if Drug=="OXYCONTIN 10 MG TER"
replace OpioidType=17 if Drug=="OXYCONTIN 15 MG TER"
replace OpioidType=17 if Drug=="OXYCONTIN 160 MG TER"
replace OpioidType=17 if Drug=="OXYCONTIN 20 MG TER"
replace OpioidType=17 if Drug=="OXYCONTIN 30 MG TER"
replace OpioidType=17 if Drug=="OXYCONTIN 40 MG TER"
replace OpioidType=17 if Drug=="OXYCONTIN 60 MG TER"
replace OpioidType=17 if Drug=="OXYCONTIN 80 MG TER"
replace OpioidType=17 if Drug=="PERCOCET 325 MG-10 MG TAB"
replace OpioidType=17 if Drug=="PERCOCET 325 MG-2.5 MG TAB"
replace OpioidType=17 if Drug=="PERCOCET 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="PERCOCET 325 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="PERCOCET 500 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="PERCOCET 650 MG-10 MG TAB"
replace OpioidType=17 if Drug=="PERCODAN 325 MG-4.5 MG-0.38 MG TAB"
replace OpioidType=17 if Drug=="PERCODAN 325 MG-4.8355 MG TAB"
replace OpioidType=17 if Drug=="PERCOLONE 5 MG TAB"
replace OpioidType=17 if Drug=="PERLOXX 300 MG-10 MG TAB"
replace OpioidType=17 if Drug=="PERLOXX 300 MG-2.5 MG TAB"
replace OpioidType=17 if Drug=="PERLOXX 300 MG-5 MG TAB"
replace OpioidType=17 if Drug=="PERLOXX 300 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="PRIMALEV 300 MG-2.5 MG TAB"
replace OpioidType=17 if Drug=="PRIMLEV 300 MG-10 MG TAB"
replace OpioidType=17 if Drug=="PRIMLEV 300 MG-5 MG TAB"
replace OpioidType=17 if Drug=="PRIMLEV 300 MG-7.5 MG TAB"
replace OpioidType=17 if Drug=="ROXICET 325 MG-5 MG TAB"
replace OpioidType=17 if Drug=="ROXICET 500 MG-5 MG TAB"
replace OpioidType=17 if Drug=="ROXICODONE 15 MG TAB"
replace OpioidType=17 if Drug=="ROXICODONE 30 MG TAB"
replace OpioidType=17 if Drug=="ROXICODONE 5 MG TAB"
replace OpioidType=17 if Drug=="TYLOX 500 MG-5 MG CAP"
replace OpioidType=17 if Drug=="XARTEMIS XR 325 MG-7.5 MG TER"
replace OpioidType=17 if Drug=="XOLOX 500 MG-10 MG TAB"
replace OpioidType=18 if Drug=="OPANA 1 MG/ML SOL"
replace OpioidType=18 if Drug=="OPANA 10 MG TAB"
replace OpioidType=18 if Drug=="OPANA 5 MG TAB"
replace OpioidType=18 if Drug=="OPANA ER 10 MG TER"
replace OpioidType=18 if Drug=="OPANA ER 15 MG TER"
replace OpioidType=18 if Drug=="OPANA ER 20 MG TER"
replace OpioidType=18 if Drug=="OPANA ER 30 MG TER"
replace OpioidType=18 if Drug=="OPANA ER 40 MG TER"
replace OpioidType=18 if Drug=="OPANA ER 5 MG TER"
replace OpioidType=18 if Drug=="OPANA ER 7.5 MG TER"
replace OpioidType=18 if Drug=="OXYMORPHONE 10 MG TAB"
replace OpioidType=18 if Drug=="OXYMORPHONE 10 MG TER"
replace OpioidType=18 if Drug=="OXYMORPHONE 15 MG TER"
replace OpioidType=18 if Drug=="OXYMORPHONE 20 MG TER"
replace OpioidType=18 if Drug=="OXYMORPHONE 30 MG TER"
replace OpioidType=18 if Drug=="OXYMORPHONE 40 MG TER"
replace OpioidType=18 if Drug=="OXYMORPHONE 5 MG TAB"
replace OpioidType=18 if Drug=="OXYMORPHONE 5 MG TER"
replace OpioidType=18 if Drug=="OXYMORPHONE 7.5 MG TER"
replace OpioidType=19 if Drug=="TALWIN LACTATE 30 MG/ML SOL"
replace OpioidType=19 if Drug=="TALACEN 650 MG-25 MG TAB"
replace OpioidType=19 if Drug=="TALWIN CPD 325 MG-12.5 MG TAB"
replace OpioidType=19 if Drug=="TALWIN NX 0.5 MG-50 MG TAB"
replace OpioidType=19 if Drug=="APAP/PENTAZOCINE 650 MG-25 MG TAB"
replace OpioidType=19 if Drug=="NALOXONE/PENTAZOCINE 0.5 MG-50 MG TAB"
replace OpioidType=19 if Drug=="PENTAZOCINE  AND ACETA 650 MG-25 MG TAB"
replace OpioidType=19 if Drug=="PENTAZOCINE -APAP 650 MG-25 MG TAB"
replace OpioidType=19 if Drug=="PENTAZOCINE -NALOXONE 0.5 MG-50 MG TAB"
replace OpioidType=19 if Drug=="PENTAZOCINE/NALOXONE 0.5 MG-50 MG TAB"
replace OpioidType=21 if Drug=="ULTIVA 1 MG PDS"
replace OpioidType=21 if Drug=="ULTIVA 5 MG PDS"
replace OpioidType=22 if Drug=="NUCYNTA 100 MG TAB"
replace OpioidType=22 if Drug=="NUCYNTA 50 MG TAB"
replace OpioidType=22 if Drug=="NUCYNTA 75 MG TAB"
replace OpioidType=22 if Drug=="NUCYNTA ER 100 MG TER"
replace OpioidType=22 if Drug=="NUCYNTA ER 150 MG TER"
replace OpioidType=22 if Drug=="NUCYNTA ER 200 MG TER"
replace OpioidType=22 if Drug=="NUCYNTA ER 250 MG TER"
replace OpioidType=22 if Drug=="NUCYNTA ER 50 MG TER"
replace OpioidType=23 if Drug=="APAP/TRAMADOL 325 MG-37.5 MG TAB"
replace OpioidType=23 if Drug=="APAP-TRAMADOL 325 MG-37.5 MG TAB"
replace OpioidType=23 if Drug=="CONZIP 100 MG CER"
replace OpioidType=23 if Drug=="CONZIP 200 MG CER"
replace OpioidType=23 if Drug=="CONZIP 300 MG CER"
replace OpioidType=23 if Drug=="RYBIX ODT 50 MG ODT"
replace OpioidType=23 if Drug=="RYZOLT 100 MG TER"
replace OpioidType=23 if Drug=="RYZOLT 200 MG TER"
replace OpioidType=23 if Drug=="RYZOLT 300 MG TER"
replace OpioidType=23 if Drug=="TRAMADOL  AND ACETAM 325 MG-37.5 MG TAB"
replace OpioidType=23 if Drug=="TRAMADOL 100 MG CER"
replace OpioidType=23 if Drug=="TRAMADOL 100 MG TER"
replace OpioidType=23 if Drug=="TRAMADOL 150 MG CER"
replace OpioidType=23 if Drug=="TRAMADOL 200 MG CER"
replace OpioidType=23 if Drug=="TRAMADOL 200 MG TER"
replace OpioidType=23 if Drug=="TRAMADOL 300 MG CER"
replace OpioidType=23 if Drug=="TRAMADOL 300 MG TER"
replace OpioidType=23 if Drug=="TRAMADOL 50 MG TAB"
replace OpioidType=23 if Drug=="TRAMADOL -APAP 325 MG-37.5 MG TAB"
replace OpioidType=23 if Drug=="TRAMADOL/ACETAMINOPH 325 MG-37.5 MG TAB"
replace OpioidType=23 if Drug=="TRAMADOL/APAP 325 MG-37.5 MG TAB"
replace OpioidType=23 if Drug=="ULTRACET 325 MG-37.5 MG TAB"
replace OpioidType=23 if Drug=="ULTRAM 50 MG TAB"
replace OpioidType=23 if Drug=="ULTRAM ER 100 MG TER"
replace OpioidType=23 if Drug=="ULTRAM ER 200 MG TER"
replace OpioidType=23 if Drug=="ULTRAM ER 300 MG TER"

replace OpioidType=1 if strpos(TherClassDesc, "Buprenorphine")!=0 & OpioidType==.
replace OpioidType=2 if strpos(TherClassDesc, "Butorphanol")!=0 & OpioidType==.
replace OpioidType=3 if strpos(TherClassDesc, "Codeine")!=0 & OpioidType==.
replace OpioidType=6 if strpos(TherClassDesc, "Dihydrocodeine")!=0 & OpioidType==.
replace OpioidType=7 if strpos(TherClassDesc, "Diphenoxylate")!=0 & OpioidType==.
replace OpioidType=8 if strpos(TherClassDesc, "Fentanyl")!=0 & OpioidType==.
replace OpioidType=9 if strpos(TherClassDesc, "Hydrocod")!=0 & OpioidType==.
replace OpioidType=10 if strpos(TherClassDesc, "Hydromorphone")!=0 & OpioidType==.
replace OpioidType=11 if strpos(TherClassDesc, "Levorphanol")!=0 & OpioidType==.
replace OpioidType=12 if strpos(TherClassDesc, "Meperidine")!=0 & OpioidType==.
replace OpioidType=13 if strpos(TherClassDesc, "Methadone")!=0 & OpioidType==.
replace OpioidType=14 if strpos(TherClassDesc, "Morphine")!=0 & OpioidType==.
replace OpioidType=15 if strpos(TherClassDesc, "Nalbuphine")!=0 & OpioidType==.
replace OpioidType=16 if strpos(TherClassDesc, "Opium")!=0 & OpioidType==.
//according to Alex, Paregoric is another name for opium
replace OpioidType=16 if strpos(TherClassDesc, "Paregoric")!=0

replace OpioidType=17 if strpos(TherClassDesc, "Oxycodone")!=0 & OpioidType ==.
replace OpioidType=18 if strpos(TherClassDesc, "Oxymorphone")!=0 & OpioidType==.
replace OpioidType=19 if strpos(TherClassDesc, "Pentazocine")!=0 & OpioidType==.
replace OpioidType=22 if strpos(TherClassDesc, "Tapentadol")!=0 & OpioidType==.
replace OpioidType=23 if strpos(TherClassDesc, "Tramadol")!=0 & OpioidType==.

***** Opioid Type End ***

** MAT of Opioid **

gen MAT=99 if DrugClass==0

label define MAT 0"Pain" 1"MAT" 99 "Unassigned"
label values MAT MAT

replace MAT=1 if Drug=="BUNAVAIL 2.1 MG-0.3 MG FIL"
replace MAT=1 if Drug=="BUNAVAIL 4.2 MG-0.7 MG FIL"
replace MAT=1 if Drug=="BUNAVAIL 6.3 MG-1 MG FIL"
replace MAT=1 if Drug=="BUPRENORPHINE  AND NALOXONE 2 MG-0.5 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE  AND NALOXONE 8 MG-2 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE 2 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE 8 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE AND NALOXONE 2 MG-0.5 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE AND NALOXONE 8 MG-2 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE-NALOXONE 2 MG-0.5 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE-NALOXONE 8 MG-2 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE/NALOXON 2 MG-0.5 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE/NALOXON 8 MG-2 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE/NALOXONE 2 MG-0.5 MG TAB"
replace MAT=1 if Drug=="BUPRENORPHINE/NALOXONE 8 MG-2 MG TAB"
replace MAT=1 if Drug=="METHADONE  CONCENTRATE 10 MG/ML SOL"
replace MAT=1 if Drug=="METHADONE  INTENSOL 10 MG/ML SOL"
replace MAT=1 if Drug=="METHADONE 10 MG/5 ML SOL"
replace MAT=1 if Drug=="METHADONE 10 MG/ML SOL"
replace MAT=1 if Drug=="METHADONE 5 MG/5 ML SOL"
replace MAT=1 if Drug=="METHADOSE 10 MG/ML SOL"
replace MAT=1 if Drug=="SUBOXONE 12 MG-3 MG FIL"
replace MAT=1 if Drug=="SUBOXONE 2 MG-0.5 MG FIL"
replace MAT=1 if Drug=="SUBOXONE 2 MG-0.5 MG TAB"
replace MAT=1 if Drug=="SUBOXONE 4 MG-1 MG FIL"
replace MAT=1 if Drug=="SUBOXONE 8 MG-2 MG FIL"
replace MAT=1 if Drug=="SUBOXONE 8 MG-2 MG TAB"
replace MAT=1 if Drug=="SUBUTEX 2 MG TAB"
replace MAT=1 if Drug=="SUBUTEX 8 MG TAB"
replace MAT=1 if Drug=="ZUBSOLV 1.4 MG-0.36 MG TAB"
replace MAT=1 if Drug=="ZUBSOLV 11.4 MG-2.9 MG TAB"
replace MAT=1 if Drug=="ZUBSOLV 2.9 MG-0.71 MG TAB"
replace MAT=1 if Drug=="ZUBSOLV 5.7 MG-1.4 MG TAB"
replace MAT=1 if Drug=="ZUBSOLV 8.6 MG-2.1 MG TAB"
replace MAT=1 if Drug=="ZUBSOLV 0.7 MG-0.18 MG TAB"

** MAT by ZYF.  ***
gen DrugFormulation = substr(Drug, -3, .)
//buprenorphine  Butrans patch is for pain
replace MAT=0 if TherClassDesc == "Buprenorphine & Comb." & DrugFormulation=="TDM" 

// belbuca film (buprenorphine) is for pain 
replace MAT=0 if TherClassDesc == "Buprenorphine & Comb." & DrugFormulation=="FIL" & strpos(Drug, "BELBUCA")!=0 

// buprenorphine inject solution & buprenex for pain
replace MAT=0 if TherClassDesc=="Buprenorphine & Comb." & DrugFormulation=="SOL" 

//Methadone solution: MAT
replace MAT=1 if TherClassDesc == "Methadone" & DrugFormulation == "SOL" & MAT==99

tab TherClassDesc if MAT==99
// And all other opioids are for pain. butorphanol, codeine, dihydrocodeine, diphenoxylate, fentanyl, hydrocodone...

replace MAT=0 if  MAT==99

** Once received MAT, category this patient to MAT
egen OUD = max(MAT), by(PatientGroupIDHash)
replace OUD = 0 if OUD == .

// clean by 0.01% rules (data entry errors)
replace PatientAge=. if PatientAge>116
replace PatientAge=. if PatientAge<=0
replace PatientSex=. if PatientSex==0
replace PaymentType=. if PaymentType==99
replace PaymentType=. if PaymentType==0
replace NumOfRefillsAuth=. if NumOfRefillsAuth<0
replace RefillCode=. if RefillCode<0
replace Quantity=. if Quantity<=0
replace DaysSupply=. if DaysSupply<=0

** gaba miligram 
gen GabaStrength = substr(Drug, -10, 3) if TherClassDesc == "Gabapentin"
replace GabaStrength = "50" if GabaStrength=="G/5"
destring GabaStrength, replace
replace GabaStrength = 565 if Drug == "GRALISE STARTER PACK 300 MG; 600 MG TAB" | Drug == "GRALISE 300 MG; 600 MG TAB"
gen GabaTotal = GabaStrength * Quantity
label var GabaTotal "Total Dose (mg) for each Rx"
gen GabaDaily = GabaStrength * Quantity / DaysSupply
label var GabaDaily "Daily dose for each Rx"
* * Gabapentin starter pack. 30-Day Starter Pack: Blister package containing 78 tablets: 9 x 300 mg tablets and 69 x 600 mg tablets
replace GabaTotal = 44100 if Drug == "GRALISE STARTER PACK 300 MG; 600 MG TAB" | Drug == "GRALISE 300 MG; 600 MG TAB"
replace GabaDaily = 44100/DaysSupply if Drug == "GRALISE STARTER PACK 300 MG; 600 MG TAB" | Drug == "GRALISE 300 MG; 600 MG TAB"

* 642 fills have 0 DaysSupply.
summarize GabaDaily, d
tab GabaDaily
tab GabaDaily, m
graph box GabaDaily, saving(Gaba_boxplot, replace)

*** Saved Data: Gaba **
save "G:\Gabapentin\statadata\gaba_dec_mar.dta", replace
log close
